# Generated by Django 3.2.5 on 2021-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20210820_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(to='bboard.Spare'),
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
