# Generated by Django 3.2.5 on 2021-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20210814_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
