# Generated by Django 3.2.5 on 2021-08-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20210820_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='spare',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.DeleteModel(
            name='RevRubric',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
