# Generated by Django 3.2.5 on 2021-08-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_spare_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
