# Generated by Django 3.2.5 on 2021-08-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_revrubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.machine')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.spare')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(through='bboard.Kit', to='bboard.Spare'),
        ),
    ]
