# Generated by Django 3.2.5 on 2021-08-22 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_auto_20210821_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'invalid': 'Неправильное название товара'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
