# Generated by Django 3.2.5 on 2021-08-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_bbcodemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbcodemodel',
            options={'verbose_name': 'Объявление BBC', 'verbose_name_plural': 'Объявления BBC'},
        ),
    ]
