# Generated by Django 3.2.5 on 2021-08-23 10:53

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_bbcodemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=bboard.models.get_timestamp_path, verbose_name='Файл')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('archive', models.FileField(upload_to='archives/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файл',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=bboard.models.get_timestamp_path, verbose_name='Изображение')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
