# Generated by Django 3.2.5 on 2021-08-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_anyfile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anyfile',
            old_name='img',
            new_name='any_file',
        ),
    ]
